site_name: Conferia
site_url: https://conferia.net

nav:
  - Conferia: index.md

theme:
  name: material
  palette:
    primary: lime
  features:
    
  icon:
    logo: material/home

markdown_extensions:
  - attr_list

